### ISSUE TITLE
The training process is much more time-consuming than other VQA systems.

### ISSUE THREAD

**Issue by cengzy14** [yuzcccc/vqa-mfb#7]
In others paper, such as Bottom-Up Attention,training one network usually converges in 12-18 epochs, which takes in the order of 12-18 hours on a single Nvidia K40 GPU. However, this model takes me at least 9 hours to train an epoch, how many hours do you take in your side? Thanks!

**Comment by yuzcccc** [comment]
The training time for 1 epoch (VQA-2.0) is about 2 hours with a TitanXP GPU. However, since the input data format is not well optimized, it takes a lot of time reading the visual features (each image feature is a .npz file, which is I/O costly). To speed up, you may have the following solutions;  1) using a workstation with large memory (mine is 128G) may also help, since the visual features will be cached and the loading speed is relatively fast.; 2) reorganize the input feature to a more efficient format, e.g., HDF5;  3) try to use multi-thread data loading, which is implement in the 3rdparty pytorch implementation [here](https://github.com/asdf0982/vqa-mfb.pytorch);
